version: '3.7'
services:
  ipmi-fan-auto-speed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ipmi-fan-auto-speed
    ports:
      - $30225:8080  # custom the port in environment variables in the Portainer stack.
    environment:
      - IPMI_IP=${IPMI_IP}
      - IPMI_USER=${IPMI_USER}
      - IPMI_PASS=${IPMI_PASS}
    volumes:
      - ./scripts:/app/scripts
    command: python -u /app/scripts/Fan_Adjustment_for_System_TemperatureV4.py
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
